### ISSUE TITLE
[Question] Is there a schedule to cut new releases?

### ISSUE THREAD

**Issue by bkinzle** [aiven/gcs-connector-for-apache-kafka#226]
I see there have been commits in the past 1.5 years but no new release.  Would be very appreciative of a new release even if it's just a patch that contains dependency updates to cleanup vulnerabilities!

**Comment by ivanyu** [comment]
Hi!

We're not aware of any vulnerability being fixed by the recently updated dependencies. That's why we didn't really rush with new releases. However, worry not: we're coming with a functional bug fix (same as https://github.com/aiven/s3-connector-for-apache-kafka/pull/224) and there will be a release soon after.
